FROM docker.io/nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04
# FROM stablebaselines/stable-baselines

RUN apt update && \
    apt install -y libopenmpi-dev git task-spooler htop nvtop btop python3.11 python3.11-venv libgl1 libglib2.0-0

